MACOSX_SDK_VERSION:    # [osx]
  - "13.3"             # [osx]
cxx_compiler_version:  # [osx]
  - 17                 # [osx]
c_compiler:            # [win]
  - vs2019             # [win]
cxx_compiler:          # [win]
  - vs2019             # [win]
