CONDA_BUILD_SYSROOT:     # [osx and x86_64]
  - /opt/MacOSX13.3.sdk  # [osx and x86_64]

MACOSX_SDK_VERSION:    # [osx]
  - "13.3"             # [osx]
cxx_compiler_version:  # [osx]
  - 17                 # [osx]

macos_min_version:         # [osx and x86_64]
  - 13.0                   # [osx and x86_64]
MACOSX_DEPLOYMENT_TARGET:  # [osx and x86_64]
  - 13.0                   # [osx and x86_64]

c_compiler:            # [win]
  - vs2019             # [win]
cxx_compiler:          # [win]
  - vs2019             # [win]
