{% set name = "mysql" %}
{% set major_minor_version = "5.7" %}
{% set micro_version = "24" %}
{% set sha256 = "b980dced9c9eb3385cca44870facc220504ca011196c5a19c2bfe43d3f5d6212" %}
{% set sha256_boost = "47f11c8844e579d02691a607fbd32540104a9ac7a2534a8ddaef50daf502baac" %}

package:
  name: {{ name|lower }}
  version: {{ major_minor_version }}.{{ micro_version }}

source:
  - url: https://dev.mysql.com/get/Downloads/MySQL-{{ major_minor_version }}/mysql-boost-{{ major_minor_version }}.{{ micro_version }}.tar.gz
    sha256: {{ sha256 }}
    patches:
      - 0001-Split-ENV_CPPFLAGS-into-separate-arguments.patch
      - fix_osx11sdk.patch
build:
  number: 1
  skip: True  # [win or s390x]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
    - make
    - perl
    - patchelf  # [not osx]
    - patch       # [not win]
    - m2-patch    # [win]
  host:
    - libedit
    - openssl
    - cyrus-sasl  # [not win]
test:
  commands:
    - mysql_config --version
    - my_print_defaults --version
    - mysqld --help --verbose
    - command -v mysql.server

about:
  home: https://www.mysql.com/
  license: GPL-2.0
  license_family: GPL
  license_file: COPYING
  summary: 'Open source relational database management system.'
  description: |
    The MySQL(TM) software delivers a very fast, multi-threaded, multi-user,
    and robust SQL (Structured Query Language) database server. MySQL Server
    is intended for mission-critical, heavy-load production systems as well
    as for embedding into mass-deployed software.

extra:
  recipe-maintainers:
    - beckermr
    - mingwandroid
